#  GNU License (C) 2025 LaSa, DIMES, Univerity of Calabria

# This program is developed for LaSa, DIMES, Univerity of Calabria. 
# Its copy, use, redistribution or modification is prohibited, or requires
# you to ask for permission. All authorized modifications made to 
# the software are subject to the same conditions as the original software.
# This program is provided as is: WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# For a copy of the complete license please contact elqemmah.ay@dimes.unical.it.

# Minimal notes added; program logic unchanged.

control : { 
            'feedback_gain'    : [ 36.38497699, 0, 0, 48.31898852, 0, 0, 
                                    0, 36.36882206, 0, 0, 48.31492434, 0,
                                    0, 0, 1.68748, 0, 0, 2.17242],

            'feedforward_gain' : [ 4.79184, 0.0, 0.0, 
                                   0.0, 4.78888,   0.0,
                                   0.0, 0.0, 0.2222],

            'output_matrix'    : [ 1, 0, 0, 0, 0, 0, 
                                   0, 1, 0, 0, 0, 0,
                                   0, 0, 1, 0, 0, 0]
          }

